name: docs

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.8"]

    timeout-minutes: 30

    steps:
    - uses: actions/checkout@main
    - uses: actions/setup-python@main
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run:  pip install tox
    - name: Generate Documentation
      run: tox -e docs
