name: CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:

jobs:
  run:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8]

    timeout-minutes: 30

    steps:
    - uses: actions/checkout@main
    - uses: actions/setup-python@main
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run:  pip install tox
    - name: Code style Check
      run:  tox -e precommit
    - name: Unit tests and coverage
      run: |
        tox -e py${{ matrix.python-version }}
    - name: Generate Documentation
      run: tox -e docs