name: test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.8"]

    timeout-minutes: 30

    steps:
    - uses: actions/checkout@main
    - uses: actions/setup-python@main
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run:  pip install tox
    - name: Unit tests and coverage
      run: |
        pyver=`echo ${{ matrix.python-version }} | tr -d "."`
        tox -e py${{ matrix.python-version }}
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true
