name: test GPT

on: workflow_dispatch

jobs:
  run:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10"]

    timeout-minutes: 30

    steps:
    - uses: actions/checkout@main
    - uses: actions/setup-python@main
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -e .
    - name: Unit tests and coverage
      run: |
        pytest test_gpt.py \
        --doctest-modules \
        nl2ltl tests \
        --cov=nl2ltl \
        --cov-report=xml \
        --cov-report=html \
        --cov-report=term \
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true
